default: &default
  schema_search_path: public, org_data
  adapter: postgresql
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  database: <%= ENV.fetch("POSTGRES_DB") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

test:
  <<: *default

development:
  <<: *default
